### ISSUE TITLE
Error: Call to undefined function apache_get_modules()

### ISSUE THREAD

**Issue by ohnese** [ahmetsacan/dokuwiki-plugin-redirectssl#1]
I get the following errors when activating the plugin:
2024-11-26 14:37:54Error: Call to undefined function apache_get_modules()/www/htdocs/w01edd89/kg-ws.de/doku/lib/plugins/redirectssl/action.php(81)
    #0 /www/htdocs/w01edd89/kg-ws.de/doku/lib/plugins/redirectssl/action.php(35): action_plugin_redirectssl->hasssl()
    #1 /www/htdocs/w01edd89/kg-ws.de/doku/inc/Extension/EventHandler.php(80): action_plugin_redirectssl->handle_action(Object(dokuwiki\Extension\Event), Array)
    #2 /www/htdocs/w01edd89/kg-ws.de/doku/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #3 /www/htdocs/w01edd89/kg-ws.de/doku/inc/ActionRouter.php(83): dokuwiki\Extension\Event->advise_before()
    #4 /www/htdocs/w01edd89/kg-ws.de/doku/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction('show')
    #5 /www/htdocs/w01edd89/kg-ws.de/doku/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /www/htdocs/w01edd89/kg-ws.de/doku/inc/actions.php(19): dokuwiki\ActionRouter::getInstance(true)
    #7 /www/htdocs/w01edd89/kg-ws.de/doku/doku.php(131): act_dispatch()
    #8 {main}
2024-11-26 14:41:08Error: Call to undefined function apache_get_modules()/www/htdocs/w01edd89/kg-ws.de/doku/lib/plugins/redirectssl/action.php(81)
    #0 /www/htdocs/w01edd89/kg-ws.de/doku/lib/plugins/redirectssl/action.php(35): action_plugin_redirectssl->hasssl()
    #1 /www/htdocs/w01edd89/kg-ws.de/doku/inc/Extension/EventHandler.php(80): action_plugin_redirectssl->handle_action(Object(dokuwiki\Extension\Event), Array)
    #2 /www/htdocs/w01edd89/kg-ws.de/doku/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #3 /www/htdocs/w01edd89/kg-ws.de/doku/inc/ActionRouter.php(83): dokuwiki\Extension\Event->advise_before()
    #4 /www/htdocs/w01edd89/kg-ws.de/doku/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction('show')
    #5 /www/htdocs/w01edd89/kg-ws.de/doku/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /www/htdocs/w01edd89/kg-ws.de/doku/inc/actions.php(19): dokuwiki\ActionRouter::getInstance(true)
    #7 /www/htdocs/w01edd89/kg-ws.de/doku/doku.php(131): act_dispatch()
    #8 {main}

**Comment by ahmetsacan** [comment]
I am surprised by this error. In action.php Lines 79-81, the function apache_get_modules() is enclosed in a try...catch block, the error you are referring to should not appear. 
Your options:
1. If you are sure you have set up your SSL and your https:// website works, you may also set checkssl=false in your plugin configuration setting, which will avoid trying to determine whether the SSL exists. 
2. I just added function_exists() as an additional check to avoid this error. You may also use the latest version and let me know if it resolves the issue.

**Comment by ohnese** [comment]
Thanks for attending to this issue.
I installed the latest version, which fixed the above error but got me a new one:

2025-01-15 21:48:11Error: Call to undefined function socket_create()/www/htdocs/w01edd89/kg-ws.de/doku/lib/plugins/redirectssl/action.php(84)
    #0 /www/htdocs/w01edd89/kg-ws.de/doku/lib/plugins/redirectssl/action.php(34): action_plugin_redirectssl->hasssl()
    #1 /www/htdocs/w01edd89/kg-ws.de/doku/inc/Extension/EventHandler.php(80): action_plugin_redirectssl->handle_action(Object(dokuwiki\Extension\Event), Array)
    #2 /www/htdocs/w01edd89/kg-ws.de/doku/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #3 /www/htdocs/w01edd89/kg-ws.de/doku/inc/ActionRouter.php(83): dokuwiki\Extension\Event->advise_before()
    #4 /www/htdocs/w01edd89/kg-ws.de/doku/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction('admin')
    #5 /www/htdocs/w01edd89/kg-ws.de/doku/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #6 /www/htdocs/w01edd89/kg-ws.de/doku/inc/actions.php(19): dokuwiki\ActionRouter::getInstance(true)
    #7 /www/htdocs/w01edd89/kg-ws.de/doku/doku.php(131): act_dispatch()
    #8 {main}

**Comment by ahmetsacan** [comment]
ok. I have updated to handle when socket_create() is not available.

Again, these errors could also be avoided by turning of the checkssl option in the plugin settings (available on Dokuwiki Adminstration -> Configuration Settings).

**Comment by ohnese** [comment]
Works like a charm now! Thanks for fixing! :)  💯 🥇
